# PK constraints

ALTER TABLE HSS_ACCESS
 ADD (CONSTRAINT HSS_ACCESS_PK PRIMARY KEY 
  (ACCESS_ID));


ALTER TABLE HSS_ACCESS_CATEGORY
 ADD (CONSTRAINT HSS_ACCESS_CATEGORY_PK PRIMARY KEY 
  (ACCESS_ID, CATEGORY_ID));
  
  
ALTER TABLE HSS_CATEGORY
 ADD (CONSTRAINT HSS_CATEGORY_PK PRIMARY KEY 
  (CATEGORY_ID));
  
  
ALTER TABLE HSS_CENSUS
 ADD (CONSTRAINT HSS_CENSUS_PK PRIMARY KEY 
  (CENSUS_ID));
  
  
ALTER TABLE HSS_CENSUS_ITEM
 ADD (CONSTRAINT HSS_CENSUS_ITEM_PK PRIMARY KEY 
  (CENSUS_ITEM_ID));
  
  
ALTER TABLE HSS_CONTACT_DETAIL
 ADD (CONSTRAINT HSS_CONTACT_DETAIL_PK PRIMARY KEY 
  (CONTACT_DETAIL_ID));
  
  
ALTER TABLE HSS_HOSPITAL
 ADD (CONSTRAINT HSS_HOSPITAL_PK PRIMARY KEY 
  (HOSPITAL_ID));
  
  
ALTER TABLE HSS_LOOKUP
 ADD (CONSTRAINT HSS_LOOKUP_PK PRIMARY KEY 
  (LOOKUP_ID));
  
  
ALTER TABLE HSS_PROGRAM
 ADD (CONSTRAINT HSS_PROGRAM_PK PRIMARY KEY 
  (PROGRAM_ID));
  
  
ALTER TABLE HSS_ROLE
 ADD (CONSTRAINT HSS_ROLE_PK PRIMARY KEY 
  (ROLE_ID));
  
  
ALTER TABLE HSS_ROLE_TYPE
 ADD (CONSTRAINT HSS_ROLE_TYPE_PK PRIMARY KEY 
  (ROLE_TYPE_ID));
  
  
ALTER TABLE HSS_STUDENT
 ADD (CONSTRAINT HSS_STUDENT_PK PRIMARY KEY 
  (STUDENT_ID));
  
  
ALTER TABLE HSS_STUDENT_ATTACHMENT
 ADD (CONSTRAINT HSS_STUDENT_ATTACHMENT_PK PRIMARY KEY 
  (ATTACHMENT_ID));
  
  
ALTER TABLE HSS_STUDENT_HISTORY
 ADD (CONSTRAINT HSS_STUDENT_HISTORY_PK PRIMARY KEY 
  (HISTORY_ID));
  
  
ALTER TABLE HSS_TEACHER
 ADD (CONSTRAINT HSS_TEACHER_PK PRIMARY KEY 
  (TEACHER_ID));
  
  
# FK Constraints

ALTER TABLE HSS_ACCESS ADD (CONSTRAINT
 HSS_ACCESS_FK1 FOREIGN KEY 
  (STUDENT_ID) REFERENCES HSS_STUDENT
  (STUDENT_ID));
  
  
ALTER TABLE HSS_ACCESS_CATEGORY ADD (CONSTRAINT
 HSS_ACCESS_CATEGORY_FK1 FOREIGN KEY 
  (CATEGORY_ID) REFERENCES HSS_CATEGORY
  (CATEGORY_ID));
  
  
ALTER TABLE HSS_ACCESS_CATEGORY ADD (CONSTRAINT
 HSS_ACCESS_CATEGORY_FK2 FOREIGN KEY 
  (ACCESS_ID) REFERENCES HSS_ACCESS
  (ACCESS_ID));
  
  
ALTER TABLE HSS_CONTACT_DETAIL ADD (CONSTRAINT
 HSS_CONTACT_DETAIL_FK1 FOREIGN KEY 
  (STUDENT_ID) REFERENCES HSS_STUDENT
  (STUDENT_ID));
  

ALTER TABLE HSS_CONTACT_DETAIL ADD (CONSTRAINT
 HSS_CONTACT_DETAIL_FK2 FOREIGN KEY 
  (ROLE_ID) REFERENCES HSS_ROLE
  (ROLE_ID));
  
  
ALTER TABLE HSS_ROLE ADD (CONSTRAINT
 HSS_ROLE_FK1 FOREIGN KEY 
  (ROLE_TYPE_ID) REFERENCES HSS_ROLE_TYPE
  (ROLE_TYPE_ID));
  
  
ALTER TABLE STUDENT_LOOKUP
 ADD CONSTRAINT STUDENT_LOOKUP_PK PRIMARY KEY 
  (STUDENT_LOOKUP_ID);
  
  
ALTER TABLE STUDENT_LOOKUP ADD CONSTRAINT
 STUDENT_LOOKUP_FK1 FOREIGN KEY 
  (STUDENT_ID) REFERENCES HSS_STUDENT
  (STUDENT_ID);
  
ALTER TABLE STUDENT_LOOKUP ADD CONSTRAINT
 STUDENT_LOOKUP_FK2 FOREIGN KEY 
  (LOOKUP_ID) REFERENCES HSS_LOOKUP
  (LOOKUP_ID);
  
  
  
  