
CREATE INDEX HSS_ACCESS_FK1_I ON HSS_ACCESS
 (STUDENT_ID);
 
 
CREATE INDEX HSS_ACCESS_CATEGORY_FK1_I ON HSS_ACCESS_CATEGORY
 (CATEGORY_ID);
 
 
CREATE INDEX HSS_ACCESS_CATEGORY_FK2_I ON HSS_ACCESS_CATEGORY
 (ACCESS_ID);
 
 
CREATE INDEX HSS_CONTACT_DETAIL_FK1_I ON HSS_CONTACT_DETAIL
 (STUDENT_ID);
 
 
CREATE INDEX HSS_CONTACT_DETAIL_FK2_I ON HSS_CONTACT_DETAIL
 (ROLE_ID);
 

CREATE INDEX HSS_ROLE_FK2_I ON HSS_ROLE
 (ROLE_TYPE_ID);
 
 
CREATE INDEX STUDENT_LOOKUP_FK1_I ON STUDENT_LOOKUP
 (STUDENT_ID);
 
CREATE INDEX STUDENT_LOOKUP_FK2_I ON STUDENT_LOOKUP
 (LOOKUP_ID);